name: Upload DTU scripts to release
on:
  push:
    tags: ['*']

permissions:
  contents: write

jobs:
  upload-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Upload DTU-Custom scripts to release
        uses: svenstaro/upload-release-action@6b7fa9f267e90b50a19fef07b3596790bb941741  # v2.11.3
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: DTU-Custom/**/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
